"""
First_migration

Revision ID: 5de80289a8f4
Revises: 
Create Date: 2024-12-16 17:50:01.663292

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5de80289a8f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False, comment="Айди в базе данных"),
        sa.Column(
            "code",
            sa.String(length=3),
            nullable=False,
            comment="Код валюты для API, обязателен, длина кода ровно 3 символа",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Название валюты, обязателен, длина имени до 50 символов",
        ),
        sa.Column(
            "country",
            sa.String(length=100),
            nullable=False,
            comment="Страна, обязательно, длина имени страны до 100 символов",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency")
    # ### end Alembic commands ###
